# Generated by Django 5.2.1 on 2025-05-11 11:36

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/")),
                ("category", models.CharField(max_length=100)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
