# Generated by Django 5.2.1 on 2025-05-14 17:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
