# Generated by Django 5.2.1 on 2025-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
